name: Build with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc g++ python3-dev
        pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt

    - name: Compile with Nuitka
      run: |
        nuitka --standalone --follow-imports --output-dir=dist main.py

    - name: Upload compiled binary
      uses: actions/upload-artifact@v3
      with:
        name: skinnerbox-binary
        path: dist/main.dist/
