name: Build with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3️⃣ Install Dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka

    # 4️⃣ Compile with Nuitka (including templates and static directories)
    - name: Compile with Nuitka
      run: |
        nuitka --standalone --follow-imports --output-dir=dist ^
        --include-data-files="templates\\**\\*.*=templates" ^
        --include-data-files="static\\**\\*.*=static" ^
        main.py

    # 5️⃣ Upload Compiled Binary as Artifact
    - name: Upload compiled binary
      uses: actions/upload-artifact@v3
      with:
        name: skinnerbox-binary
        path: dist/main.dist/
