name: Build with Nuitka

# Trigger on pushes to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc g++ python3-dev
        pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt

    # 4. Compile code with Nuitka
    - name: Compile with Nuitka
      run: |
        nuitka --standalone --follow-imports --output-dir=dist main.py

    # 5. Upload the compiled binary as an artifact
    - name: Upload compiled binary
      uses: actions/upload-artifact@v3
      with:
        name: skinnerbox-binary
        path: dist/main.dist/
