name: PyPI Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag to release to PyPI'
        required: true
        type: string
  workflow_call:
    inputs:
      tag_name:
        description: 'The tag to release to PyPI'
        required: true
        type: string

jobs:
  pypi_publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/skinnerbox-source
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read   # Required for actions/checkout
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag_name || github.event.inputs.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build source and wheel distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true